Spring:
  application:
    name: project_SNSMaster

  datasource:
    url: jdbc:mysql://192.168.0.8:3306/orcl?useSSL=false&serverTimeZone=UTC
    username: codeMaster
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  servlet:
    multipart:
      enabled: true
      location: C:/tmp
    session:
      timeout: 3600

mybatis:
  mapper-locations:
    classpath:/mapper/*Mapper.xml